@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJjdXN0b21lcl9pZCI6MSwiZXhwIjoxNzg5NjU3NDg4LCJpYXQiOjE3ODk2NTY1ODh9.5IQjFOnQ9EXhDxWncw1fcD_-OWBTscEW3B4hKgbNpOI

// customers get
GET {{baseUrl}}/customers

###
#customers get by id
GET {{baseUrl}}/customers/1


###
#customers get by id
GET {{baseUrl}}/customers/1/accounts
Authorization: Bearer {{token}}


###
# customer creat
POST {{baseUrl}}/customers
Content-Type: application/json

{
  "first_name": "Mudi",
  "last_name": "Sheikh",
  "email": "mudi@example.com"
}


###
# customer accounts create
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "customer_id": 1000,
  "account_type": "SAVINGS",
  "currency": "GHS"
}

###
# customer accounts get
GET {{baseUrl}}/accounts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJjdXN0b21lcl9pZCI6MSwiZXhwIjoxNzg5NjUzODMxLCJpYXQiOjE3ODk2NTI5MzF9.DRrJdDa7Vc-8tzsvDVoIrzCTqcCtcnxszbmuNZhvXho

###
# create account
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "customer_id": 1,
  "email": "john@example.com",
  "password": "mypassword123"
}

###
# login account
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "mypassword123"
}

###
POST {{baseUrl}}/accounts/1/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": 50000
}