// customers get
GET http://localhost:8080/customers

###
#customers get by id
GET http://localhost:8080/customers/1


###
# customer creat
POST http://localhost:8080/customers
Content-Type: application/json

{
  "first_name": "Mahmud",
  "last_name": "Wunnam",
  "email": "mahmud@example.com"
}